### PR TITLE
Fixes #62 PHP 8.1 deprecation notices

### LINKED ISSUE #62: PHP 8.1.3
Hi ! 
As I tried to use OneSheet with PHP 8.1.3 (having no problems with previous versions of PHP), I faced some errors that prevented the file to be generated. I was able to make it work with these 3 changes.

File : **src/OneSheet/Sheet.php**

Error : Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

Before :
```
public function getSheetViewsXml()
    {
        if (1 !== preg_match('~^[A-Z]+(\d+)$~', $this->freezePaneCellId, $m)) {
            return '';
        }

        return sprintf(SheetXml::SHEETVIEWS_XML, array_pop($m) - 1, $this->freezePaneCellId);
    }
```

After :	
```
public function getSheetViewsXml()
    {
        if (1 !== preg_match('~^[A-Z]+(\d+)$~', $this->freezePaneCellId ?: '', $m)) {
            return '';
        }

        return sprintf(SheetXml::SHEETVIEWS_XML, array_pop($m) - 1, $this->freezePaneCellId);
    }	
```
	

File : **src/OneSheet/Sheetfile.php**

Error : Deprecated: uniqid(): Passing null to parameter #1 ($prefix) of type string is deprecated

Before :
```
public function __construct()
    {
        $this->filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid(null, 1) . '.xml';
        if (!$this->filePointer = fopen($this->filePath, 'wb+')) {
            throw new \RuntimeException("Failed to create temporary sheet file {$this->filePath}!");
        }
    }
```

After :
```
public function __construct()
    {
        $this->filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('', 1) . '.xml';
        if (!$this->filePointer = fopen($this->filePath, 'wb+')) {
            throw new \RuntimeException("Failed to create temporary sheet file {$this->filePath}!");
        }
    }	
```
	
File : **src/OneSheet/Size/SizeCalculator.php**

Error : Deprecated: is_dir(): Passing null to parameter #1 ($filename) of type string is deprecated	

Before :	
```
public function __construct($fontsDirectory = null)
    {
        if (is_dir($fontsDirectory)) {
            $this->findFonts($fontsDirectory);
        }
    }
```

After :
```
public function __construct($fontsDirectory = null)
    {
        if ($fontsDirectory != null && is_dir($fontsDirectory)) {
            $this->findFonts($fontsDirectory);
        }
    }
```

It works for what I need to do but I'm not sure if it's the best way to correct those errors.

### PR DESCRIPTION
**Pull request by nimmneun**
PHP 8.1 introduced some deprecation notices

### CODE REVIEW

**Comment by mbrodala** [comment]
@nimmneun Should this be a draft or is it ready?

**Comment by nimmneun** [comment]
ok, manually ran tests locally and everthing seems fine 👍

File: src/OneSheet/SheetFile.php [hunk 1]
```diff
@@ -21,7 +21,7 @@ class SheetFile
      */
     public function __construct()
     {
-        $this->filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid(null, 1) . '.xml';
+        $this->filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('', 1) . '.xml';
```
Comment (mbrodala) [inline src/OneSheet/SheetFile.php:24]:
```suggestion
        $this->filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('', true) . '.xml';
```

Let's also fix this while we're at it.

**Review by mbrodala — APPROVED** [review]
